# Generated by Django 4.2.11 on 2024-05-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0002_image_delete_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='UploadImg',
        ),
    ]
