# Generated by Django 4.2.11 on 2024-05-26 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0005_alter_uploadimg_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadimg',
            old_name='image_file',
            new_name='img_file',
        ),
        migrations.RemoveField(
            model_name='uploadimg',
            name='id',
        ),
        migrations.RemoveField(
            model_name='uploadimg',
            name='title',
        ),
        migrations.AddField(
            model_name='uploadimg',
            name='color',
            field=models.CharField(choices=[('1', 'синий'), ('2', 'зеленый'), ('3', 'коричневый')], default='1', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uploadimg',
            name='id_img',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadimg',
            name='plastic_type',
            field=models.CharField(choices=[('1', 'PE-C2'), ('2', 'PE-HD'), ('3', 'PE-LD'), ('4', 'PE-LLD'), ('5', 'PE-MD'), ('6', 'PE-UHMW'), ('7', 'PE-VLD'), ('8', 'PET'), ('9', 'PP'), ('10', 'PVC-C'), ('11', 'PVC-U')], default='8', max_length=10),
        ),
        migrations.AddField(
            model_name='uploadimg',
            name='title_text_img',
            field=models.CharField(default=400000, max_length=15, verbose_name='full name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadimg',
            name='visible',
            field=models.CharField(choices=[('1', 'прозрачный'), ('2', 'полупрозрачный'), ('3', 'непрозрачный')], default='2', max_length=14),
        ),
        migrations.AlterField(
            model_name='uploadimg',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
