# Generated by Django 4.2.11 on 2024-05-26 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0006_rename_image_file_uploadimg_img_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimg',
            name='id_img',
        ),
        migrations.AddField(
            model_name='uploadimg',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
