# Generated by Django 4.2.11 on 2024-05-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0007_remove_uploadimg_id_img_uploadimg_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimg',
            name='id',
        ),
        migrations.AddField(
            model_name='uploadimg',
            name='id_img',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
