# Generated by Django 4.2.11 on 2024-05-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0008_remove_uploadimg_id_uploadimg_id_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadingImg',
            fields=[
                ('id_img', models.AutoField(primary_key=True, serialize=False)),
                ('title_text_img', models.CharField(max_length=15, verbose_name='full name')),
                ('img_file', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('plastic_type', models.CharField(choices=[('1', 'PE-C2'), ('2', 'PE-HD'), ('3', 'PE-LD'), ('4', 'PE-LLD'), ('5', 'PE-MD'), ('6', 'PE-UHMW'), ('7', 'PE-VLD'), ('8', 'PET'), ('9', 'PP'), ('10', 'PVC-C'), ('11', 'PVC-U')], default='8', max_length=10)),
                ('visible', models.CharField(choices=[('1', 'прозрачный'), ('2', 'полупрозрачный'), ('3', 'непрозрачный')], default='2', max_length=14)),
                ('color', models.CharField(choices=[('1', 'синий'), ('2', 'зеленый'), ('3', 'коричневый')], default='1', max_length=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UploadImg',
        ),
    ]
