# Generated by Django 4.2.11 on 2024-05-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0009_uploadingimg_delete_uploadimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadingimg',
            name='id_img',
        ),
        migrations.RemoveField(
            model_name='uploadingimg',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='uploadingimg',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
