# Generated by Django 4.2.11 on 2024-05-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0010_remove_uploadingimg_id_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadingimg',
            name='id',
        ),
        migrations.AddField(
            model_name='uploadingimg',
            name='id_img',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadingimg',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
